### ISSUE TITLE
Нужно использовать TextField

### ISSUE THREAD

**Issue by SergeyMirvoda** [LtItb/IR-2019#1]
https://github.com/LtItb/IR-2019/blob/066d51dab6d14df97c9463d35615bad6759ffd19/App/FormSearch.cs#L329

> 
>   /// A field that is indexed and tokenized, without term
>   /// vectors.  For example this would be used on a 'body'
>   /// field, that contains the bulk of a document's text.
>   /// </summary>

Когда вы делите текст пробелами вы делаете токенизацию и делаете это не совсем правильно.

**Comment by ltitbe** [comment]
@SergeyMirvoda Заменил StringField на TextField, добавил QueryParser, оставил общее поле name

**Comment by SergeyMirvoda** [comment]
Ок
