### ISSUE TITLE
Вот это тоже лишее

### ISSUE THREAD

**Issue by SergeyMirvoda** [LtItb/IR-2019#2]
Звёздочки не нужно использовать.
Попробуйте без них.
Должно работать по умолчанию именно так и без звёздочек

https://github.com/LtItb/IR-2019/blob/066d51dab6d14df97c9463d35615bad6759ffd19/App/FormSearch.cs#L218

**Comment by ltitbe** [comment]
@SergeyMirvoda убрал звёздочки
